# Generated by Django 5.0.1 on 2024-01-20 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_products_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='products',
            name='image',
            field=models.ImageField(blank=True, default='static/img/', null=True, upload_to='static/img/'),
        ),
    ]
